import React from 'react';

// Combined explore posts from all previous files
const combinedExplorePosts = [
  // Posts from ExplorePosts.jsx (e39-e52)
  {
    id: 'e39',
    type: 'gallery',
    category: 'streetfood',
    user: {
      name: 'Street Food Explorer',
      username: 'streetfoodexplorer',
      avatar: 'https://i.pravatar.cc/150?img=43',
      verified: true,
    },
    content: 'Street food markets in Asia that will blow your taste buds away 🌮🍜',
    media: [
      'https://source.unsplash.com/random/600x400?streetfood1',
      'https://source.unsplash.com/random/600x400?streetfood2',
      'https://source.unsplash.com/random/600x400?streetfood3'
    ],
    time: '24d',
    likes: 9876,
    comments: 456,
    shares: 789,
    trending: true,
  },
  {
    id: 'e40',
    type: 'short',
    category: 'lifehack',
    user: {
      name: 'Life Hacker',
      username: 'lifehacker',
      avatar: 'https://i.pravatar.cc/150?img=55',
      verified: true,
    },
    content: 'How to fold a fitted sheet perfectly in under 30 seconds! ✨',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?housework',
    duration: '0:25',
    time: '25d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e41',
    type: 'image',
    category: 'art',
    user: {
      name: 'Art Gallery',
      username: 'artgallery',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'Contemporary art installation that plays with light and shadows',
    media: 'https://source.unsplash.com/random/600x400?contemporaryart',
    time: '1d',
    likes: 12543,
    comments: 783,
    shares: 2145,
    trending: true,
  },
  {
    id: 'e42',
    type: 'video',
    category: 'science',
    user: {
      name: 'Science Today',
      username: 'sciencetoday',
      avatar: 'https://i.pravatar.cc/150?img=62',
      verified: true,
    },
    content: 'Watch what happens when you mix these two chemicals together! 🧪',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?chemistry',
    duration: '3:45',
    time: '2d',
    likes: 9875,
    comments: 876,
    shares: 1432,
    trending: true,
  },
  {
    id: 'e43',
    type: 'note',
    category: 'philosophy',
    user: {
      name: 'Deep Thoughts',
      username: 'deepthoughts',
      avatar: 'https://i.pravatar.cc/150?img=39',
      verified: true,
    },
    content: '✨ Philosophical Question ✨\n\n"If a tree falls in a forest and no one is around to hear it, does it make a sound?"\n\nWhat are your thoughts?',
    background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    textColor: 'dark',
    time: '3d',
    likes: 8765,
    comments: 1543,
    shares: 432,
    trending: true,
  },
  
  // Posts from MoreExplorePosts.jsx (e53-e70)
  {
    id: 'e53',
    type: 'image',
    category: 'nature',
    user: {
      name: 'Nature Photography',
      username: 'naturephotography',
      avatar: 'https://i.pravatar.cc/150?img=37',
      verified: true,
    },
    content: 'Rare phenomenon: bioluminescent plankton lighting up the beach at night',
    media: 'https://source.unsplash.com/random/600x400?bioluminescent',
    time: '13d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e54',
    type: 'video',
    category: 'astronomy',
    user: {
      name: 'Space Explorer',
      username: 'spaceexplorer',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'Meteor shower timelapse captured from the mountains - no filters used!',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?meteor',
    duration: '2:30',
    time: '14d',
    likes: 45678,
    comments: 3456,
    shares: 7890,
    trending: true,
  },
  {
    id: 'e55',
    type: 'note',
    category: 'poetry',
    user: {
      name: 'Poet Soul',
      username: 'poetsoul',
      avatar: 'https://i.pravatar.cc/150?img=59',
      verified: true,
    },
    content: '✨ Midnight Thoughts ✨\n\nStars whisper secrets,\nMoon keeps them safe,\nNight fades to dawn,\nBut memories remain.',
    background: 'linear-gradient(120deg, #8ec5fc 0%, #e0c3fc 100%)',
    textColor: 'dark',
    time: '15d',
    likes: 9876,
    comments: 654,
    shares: 321,
    trending: true,
  },
  
  // Selected posts from AdditionalExplorePosts.jsx (e71-e106)
  // Adding a representative sample to keep file size manageable
  {
    id: 'e71',
    type: 'image',
    category: 'fashion',
    user: {
      name: 'Style Trendsetter',
      username: 'styletrendsetter',
      avatar: 'https://i.pravatar.cc/150?img=31',
      verified: true,
    },
    content: 'The most innovative sustainable fashion designs from this year\'s eco-conscious runway',
    media: 'https://source.unsplash.com/random/600x400?sustainablefashion',
    time: '1d',
    likes: 23456,
    comments: 1432,
    shares: 2045,
    trending: true,
  },
  {
    id: 'e72',
    type: 'video',
    category: 'science',
    user: {
      name: 'Science Explained',
      username: 'scienceexplained',
      avatar: 'https://i.pravatar.cc/150?img=45',
      verified: true,
    },
    content: 'Watch what happens when we drop a red-hot nickel ball into a honeycomb',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?experiment',
    duration: '1:42',
    time: '2d',
    likes: 78901,
    comments: 6543,
    shares: 4321,
    trending: true,
  },
  {
    id: 'e73',
    type: 'gallery',
    category: 'travel',
    user: {
      name: 'World Explorer',
      username: 'worldexplorer',
      avatar: 'https://i.pravatar.cc/150?img=23',
      verified: true,
    },
    content: 'Undiscovered caves with crystal formations that look out of this world',
    media: [
      'https://source.unsplash.com/random/600x400?cave1',
      'https://source.unsplash.com/random/600x400?cave2',
      'https://source.unsplash.com/random/600x400?cave3',
      'https://source.unsplash.com/random/600x400?cave4'
    ],
    time: '3d',
    likes: 45678,
    comments: 2345,
    shares: 7890,
    trending: true,
  },
  {
    id: 'e85',
    type: 'gallery',
    category: 'food',
    user: {
      name: 'Culinary Arts',
      username: 'culinaryarts',
      avatar: 'https://i.pravatar.cc/150?img=32',
      verified: true,
    },
    content: 'Molecular gastronomy creations that look like one thing but taste like something completely different',
    media: [
      'https://source.unsplash.com/random/600x400?molecular1',
      'https://source.unsplash.com/random/600x400?molecular2',
      'https://source.unsplash.com/random/600x400?molecular3',
      'https://source.unsplash.com/random/600x400?molecular4'
    ],
    time: '15d',
    likes: 34567,
    comments: 2345,
    shares: 5678,
    trending: true,
  },
  {
    id: 'e89',
    type: 'image',
    category: 'space',
    user: {
      name: 'Space Agency',
      username: 'spaceagency',
      avatar: 'https://i.pravatar.cc/150?img=57',
      verified: true,
    },
    content: 'First high-resolution image of a black hole\'s event horizon - captured by our new space telescope',
    media: 'https://source.unsplash.com/random/600x400?blackhole',
    time: '19d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  },
  {
    id: 'e90',
    type: 'video',
    category: 'technology',
    user: {
      name: 'Future Tech',
      username: 'futuretech',
      avatar: 'https://i.pravatar.cc/150?img=52',
      verified: true,
    },
    content: 'This new holographic display allows you to interact with 3D objects in mid-air',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?hologram',
    duration: '3:18',
    time: '20d',
    likes: 78901,
    comments: 6543,
    shares: 12098,
    trending: true,
  },
  {
    id: 'e95',
    type: 'video',
    category: 'cooking',
    user: {
      name: 'Master Chef',
      username: 'masterchef',
      avatar: 'https://i.pravatar.cc/150?img=51',
      verified: true,
    },
    content: 'Three-Michelin-star chef reveals his secret technique for the perfect scrambled eggs',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?eggs',
    duration: '6:21',
    time: '25d',
    likes: 45678,
    comments: 8765,
    shares: 3456,
    trending: true,
  },
  {
    id: 'e100',
    type: 'note',
    category: 'inspiration',
    user: {
      name: 'Daily Inspire',
      username: 'dailyinspire',
      avatar: 'https://i.pravatar.cc/150?img=30',
      verified: true,
    },
    content: '✨ Thought of the Day ✨\n\n"The meaning of life is to find your gift. The purpose of life is to give it away." - Pablo Picasso\n\nWhat gift are you sharing with the world?',
    background: 'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
    textColor: 'light',
    time: '30d',
    likes: 123456,
    comments: 9876,
    shares: 54321,
    trending: true,
  },
  
  // Adding 50+ new explore posts with diverse content
  {
    id: 'e101',
    type: 'image',
    category: 'architecture',
    user: {
      name: 'Architecture Daily',
      username: 'architecturedaily',
      avatar: 'https://i.pravatar.cc/150?img=22',
      verified: true,
    },
    content: 'This building in Singapore uses vertical gardens to purify air and reduce energy consumption',
    media: 'https://source.unsplash.com/random/600x400?greenarchitecture',
    time: '5h',
    likes: 12453,
    comments: 543,
    shares: 982,
    trending: true,
  },
  {
    id: 'e102',
    type: 'video',
    category: 'dance',
    user: {
      name: 'Dance Evolution',
      username: 'danceevolution',
      avatar: 'https://i.pravatar.cc/150?img=33',
      verified: true,
    },
    content: 'The evolution of breakdancing over 50 years in under 3 minutes',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?breakdance',
    duration: '2:58',
    time: '1d',
    likes: 45231,
    comments: 2187,
    shares: 8764,
    trending: true,
  },
  {
    id: 'e103',
    type: 'gallery',
    category: 'art',
    user: {
      name: 'Modern Museum',
      username: 'modernmuseum',
      avatar: 'https://i.pravatar.cc/150?img=41',
      verified: true,
    },
    content: 'Interactive art installations that respond to your movement and emotions',
    media: [
      'https://source.unsplash.com/random/600x400?interactiveart1',
      'https://source.unsplash.com/random/600x400?interactiveart2',
      'https://source.unsplash.com/random/600x400?interactiveart3'
    ],
    time: '2d',
    likes: 28765,
    comments: 1432,
    shares: 5432,
    trending: true,
  },
  {
    id: 'e104',
    type: 'note',
    category: 'motivation',
    user: {
      name: 'Life Coach',
      username: 'lifecoach',
      avatar: 'https://i.pravatar.cc/150?img=29',
      verified: true,
    },
    content: '✨ Morning Routine ✨\n\n1. Gratitude journal - 5 min\n2. Meditation - 10 min\n3. Movement - 15 min\n4. Planning - 10 min\n\nTry this for 21 days and watch your life transform.',
    background: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    textColor: 'dark',
    time: '3d',
    likes: 56432,
    comments: 2765,
    shares: 12543,
    trending: true,
  },
  {
    id: 'e105',
    type: 'image',
    category: 'underwater',
    user: {
      name: 'Ocean Explorer',
      username: 'oceanexplorer',
      avatar: 'https://i.pravatar.cc/150?img=61',
      verified: true,
    },
    content: 'Rare sighting of a giant squid in its natural deep-sea habitat - captured at 1200m depth',
    media: 'https://source.unsplash.com/random/600x400?deepsea',
    time: '4d',
    likes: 87543,
    comments: 6543,
    shares: 21098,
    trending: true,
  },
  {
    id: 'e106',
    type: 'video',
    category: 'technology',
    user: {
      name: 'Tech Insider',
      username: 'techinsider',
      avatar: 'https://i.pravatar.cc/150?img=51',
      verified: true,
    },
    content: 'This AI can generate photorealistic portraits of people who never existed',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?aitech',
    duration: '4:28',
    time: '5d',
    likes: 35642,
    comments: 4321,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e107',
    type: 'gallery',
    category: 'fashion',
    user: {
      name: 'Fashion Forward',
      username: 'fashionforward',
      avatar: 'https://i.pravatar.cc/150?img=39',
      verified: true,
    },
    content: 'Materials of the future: clothing made from fungi, algae, and lab-grown leather',
    media: [
      'https://source.unsplash.com/random/600x400?futurefashion1',
      'https://source.unsplash.com/random/600x400?futurefashion2',
      'https://source.unsplash.com/random/600x400?futurefashion3'
    ],
    time: '6d',
    likes: 46753,
    comments: 3214,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e108',
    type: 'image',
    category: 'astronomy',
    user: {
      name: 'Cosmic Wonder',
      username: 'cosmicwonder',
      avatar: 'https://i.pravatar.cc/150?img=53',
      verified: true,
    },
    content: 'The pillars of creation - captured by the James Webb telescope in unprecedented detail',
    media: 'https://source.unsplash.com/random/600x400?space',
    time: '7d',
    likes: 98765,
    comments: 7654,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e109',
    type: 'video',
    category: 'wildlife',
    user: {
      name: 'Wildlife Channel',
      username: 'wildlifechannel',
      avatar: 'https://i.pravatar.cc/150?img=12',
      verified: true,
    },
    content: 'Rare footage of snow leopards playing in their natural habitat',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?snowleopard',
    duration: '3:12',
    time: '8d',
    likes: 76543,
    comments: 5432,
    shares: 12987,
    trending: true,
  },
  {
    id: 'e110',
    type: 'note',
    category: 'mindfulness',
    user: {
      name: 'Mindful Living',
      username: 'mindfulliving',
      avatar: 'https://i.pravatar.cc/150?img=25',
      verified: true,
    },
    content: '✨ Breathing Exercise ✨\n\nBreath in for 4 counts\nHold for 7 counts\nExhale for 8 counts\nRepeat 4 times\n\nTry this whenever you feel stressed or anxious.',
    background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    textColor: 'dark',
    time: '9d',
    likes: 45678,
    comments: 3456,
    shares: 9876,
    trending: true,
  },
  
  // Adding more posts e111-e120
  {
    id: 'e111',
    type: 'image',
    category: 'fitness',
    user: {
      name: 'Fitness Pro',
      username: 'fitnesspro',
      avatar: 'https://i.pravatar.cc/150?img=13',
      verified: true,
    },
    content: 'This 7-minute HIIT workout burns more calories than a 30-minute jog',
    media: 'https://source.unsplash.com/random/600x400?hiitworkout',
    time: '10d',
    likes: 34567,
    comments: 2345,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e112',
    type: 'video',
    category: 'culinary',
    user: {
      name: 'Chef Secrets',
      username: 'chefsecrets',
      avatar: 'https://i.pravatar.cc/150?img=27',
      verified: true,
    },
    content: 'The secret technique professional chefs use to make perfect pasta every time',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?pasta',
    duration: '5:46',
    time: '11d',
    likes: 65432,
    comments: 4321,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e113',
    type: 'gallery',
    category: 'interiordesign',
    user: {
      name: 'Modern Interiors',
      username: 'moderninteriors',
      avatar: 'https://i.pravatar.cc/150?img=42',
      verified: true,
    },
    content: 'Minimalist Japanese-inspired apartments that maximize small spaces',
    media: [
      'https://source.unsplash.com/random/600x400?japanesedecor1',
      'https://source.unsplash.com/random/600x400?japanesedecor2',
      'https://source.unsplash.com/random/600x400?japanesedecor3'
    ],
    time: '12d',
    likes: 54321,
    comments: 3210,
    shares: 7654,
    trending: true,
  },
  {
    id: 'e114',
    type: 'image',
    category: 'psychology',
    user: {
      name: 'Mind Matters',
      username: 'mindmatters',
      avatar: 'https://i.pravatar.cc/150?img=44',
      verified: true,
    },
    content: 'Visual illusions that reveal how your brain processes information',
    media: 'https://source.unsplash.com/random/600x400?opticalillusion',
    time: '13d',
    likes: 87654,
    comments: 6543,
    shares: 13456,
    trending: true,
  },
  {
    id: 'e115',
    type: 'note',
    category: 'productivity',
    user: {
      name: 'Productivity Guru',
      username: 'productivityguru',
      avatar: 'https://i.pravatar.cc/150?img=18',
      verified: true,
    },
    content: '✨ Time Management Matrix ✨\n\n1. Urgent & Important - DO NOW\n2. Important but Not Urgent - SCHEDULE\n3. Urgent but Not Important - DELEGATE\n4. Not Urgent & Not Important - ELIMINATE\n\nWhich quadrant are you spending most time in?',
    background: 'linear-gradient(120deg, #d4fc79 0%, #96e6a1 100%)',
    textColor: 'dark',
    time: '14d',
    likes: 76543,
    comments: 5432,
    shares: 16789,
    trending: true,
  },
  {
    id: 'e116',
    type: 'video',
    category: 'science',
    user: {
      name: 'Science Explained',
      username: 'scienceexplained',
      avatar: 'https://i.pravatar.cc/150?img=28',
      verified: true,
    },
    content: 'What happens when lightning strikes sand? Creating natural glass sculptures',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?lightning',
    duration: '3:42',
    time: '15d',
    likes: 56789,
    comments: 4567,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e117',
    type: 'gallery',
    category: 'streetart',
    user: {
      name: 'Urban Canvas',
      username: 'urbancanvas',
      avatar: 'https://i.pravatar.cc/150?img=35',
      verified: true,
    },
    content: 'Street art that interacts with its urban environment in clever ways',
    media: [
      'https://source.unsplash.com/random/600x400?streetart1',
      'https://source.unsplash.com/random/600x400?streetart2',
      'https://source.unsplash.com/random/600x400?streetart3',
      'https://source.unsplash.com/random/600x400?streetart4'
    ],
    time: '16d',
    likes: 98765,
    comments: 8765,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e118',
    type: 'image',
    category: 'transportation',
    user: {
      name: 'Future Transport',
      username: 'futuretransport',
      avatar: 'https://i.pravatar.cc/150?img=17',
      verified: true,
    },
    content: 'This new hyperloop prototype can travel at 700 mph, making it faster than commercial airplanes',
    media: 'https://source.unsplash.com/random/600x400?hyperloop',
    time: '17d',
    likes: 123456,
    comments: 4321,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e119',
    type: 'video',
    category: 'music',
    user: {
      name: 'Music Theory',
      username: 'musictheory',
      avatar: 'https://i.pravatar.cc/150?img=24',
      verified: true,
    },
    content: 'How film composers use music to manipulate your emotions without you realizing it',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?filmmusic',
    duration: '8:25',
    time: '18d',
    likes: 76543,
    comments: 6543,
    shares: 15432,
    trending: true,
  },
  {
    id: 'e120',
    type: 'note',
    category: 'creativity',
    user: {
      name: 'Creative Mind',
      username: 'creativemind',
      avatar: 'https://i.pravatar.cc/150?img=34',
      verified: true,
    },
    content: '✨ Creativity Prompt ✨\n\nChoose random objects around you and create a story that connects them in unexpected ways.\n\nShare your mini-story in the comments!',
    background: 'linear-gradient(120deg, #f6d365 0%, #fda085 100%)',
    textColor: 'dark',
    time: '19d',
    likes: 45678,
    comments: 8765,
    shares: 5432,
    trending: true,
  },
  
  // Adding more posts e121-e130
  {
    id: 'e121',
    type: 'image',
    category: 'technology',
    user: {
      name: 'Quantum Tech',
      username: 'quantumtech',
      avatar: 'https://i.pravatar.cc/150?img=21',
      verified: true,
    },
    content: 'First commercial quantum computer that can solve problems traditional computers find impossible',
    media: 'https://source.unsplash.com/random/600x400?quantumcomputer',
    time: '20d',
    likes: 123456,
    comments: 7890,
    shares: 34567,
    trending: true,
  },
  {
    id: 'e122',
    type: 'video',
    category: 'nature',
    user: {
      name: 'Nature Timelapse',
      username: 'naturetimelapse',
      avatar: 'https://i.pravatar.cc/150?img=15',
      verified: true,
    },
    content: 'Blooming flowers captured in 8K timelapse over 30 days and compressed to 2 minutes',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?flowertimelapse',
    duration: '2:15',
    time: '21d',
    likes: 87654,
    comments: 5432,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e123',
    type: 'gallery',
    category: 'photography',
    user: {
      name: 'Macro Photo',
      username: 'macrophoto',
      avatar: 'https://i.pravatar.cc/150?img=9',
      verified: true,
    },
    content: 'The hidden world of insects - captured with specialized macro photography',
    media: [
      'https://source.unsplash.com/random/600x400?insectmacro1',
      'https://source.unsplash.com/random/600x400?insectmacro2',
      'https://source.unsplash.com/random/600x400?insectmacro3'
    ],
    time: '22d',
    likes: 65432,
    comments: 4321,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e124',
    type: 'note',
    category: 'finance',
    user: {
      name: 'Money Matters',
      username: 'moneymatters',
      avatar: 'https://i.pravatar.cc/150?img=19',
      verified: true,
    },
    content: '✨ Financial Freedom Rules ✨\n\n1. Spend less than you earn\n2. Invest the difference\n3. Avoid debt\n4. Build multiple income streams\n5. Protect your assets\n\nWhich one are you working on right now?',
    background: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    textColor: 'dark',
    time: '23d',
    likes: 98765,
    comments: 7654,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e125',
    type: 'image',
    category: 'education',
    user: {
      name: 'Learning Hub',
      username: 'learninghub',
      avatar: 'https://i.pravatar.cc/150?img=26',
      verified: true,
    },
    content: 'This innovative school design in Finland is revolutionizing how children learn',
    media: 'https://source.unsplash.com/random/600x400?educationdesign',
    time: '24d',
    likes: 76543,
    comments: 5432,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e126',
    type: 'video',
    category: 'history',
    user: {
      name: 'History Channel',
      username: 'historychannel',
      avatar: 'https://i.pravatar.cc/150?img=36',
      verified: true,
    },
    content: 'Recently discovered footage from 1897 that shows everyday life in Victorian London',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?victorian',
    duration: '6:32',
    time: '25d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  },
  {
    id: 'e127',
    type: 'gallery',
    category: 'travel',
    user: {
      name: 'Hidden Gems',
      username: 'hiddengems',
      avatar: 'https://i.pravatar.cc/150?img=38',
      verified: true,
    },
    content: 'Lesser-known islands with pristine beaches and no tourists',
    media: [
      'https://source.unsplash.com/random/600x400?secretisland1',
      'https://source.unsplash.com/random/600x400?secretisland2',
      'https://source.unsplash.com/random/600x400?secretisland3',
      'https://source.unsplash.com/random/600x400?secretisland4'
    ],
    time: '26d',
    likes: 87654,
    comments: 6543,
    shares: 21098,
    trending: true,
  },
  {
    id: 'e128',
    type: 'image',
    category: 'sustainability',
    user: {
      name: 'Green Future',
      username: 'greenfuture',
      avatar: 'https://i.pravatar.cc/150?img=47',
      verified: true,
    },
    content: 'This floating device can clear ocean plastic and convert it into recycled materials',
    media: 'https://source.unsplash.com/random/600x400?oceancleanup',
    time: '27d',
    likes: 98765,
    comments: 8765,
    shares: 34567,
    trending: true,
  },
  {
    id: 'e129',
    type: 'video',
    category: 'psychology',
    user: {
      name: 'Brain Science',
      username: 'brainscience',
      avatar: 'https://i.pravatar.cc/150?img=56',
      verified: true,
    },
    content: 'How your brain creates and consolidates memories while you sleep',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?brainsleep',
    duration: '7:18',
    time: '28d',
    likes: 65432,
    comments: 4321,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e130',
    type: 'note',
    category: 'leadership',
    user: {
      name: 'Leadership Insights',
      username: 'leadershipinsights',
      avatar: 'https://i.pravatar.cc/150?img=14',
      verified: true,
    },
    content: '✨ Leadership Principles ✨\n\n1. Lead by example\n2. Listen more than you speak\n3. Empower others\n4. Embrace failure as learning\n5. Stay curious\n\nWhich principle resonates with you most?',
    background: 'linear-gradient(120deg, #a6c0fe 0%, #f68084 100%)',
    textColor: 'light',
    time: '29d',
    likes: 76543,
    comments: 5432,
    shares: 12345,
    trending: true,
  },
  
  // Adding more posts e131-e140
  {
    id: 'e131',
    type: 'image',
    category: 'robotics',
    user: {
      name: 'Robot Revolution',
      username: 'robotrevolution',
      avatar: 'https://i.pravatar.cc/150?img=11',
      verified: true,
    },
    content: 'This humanoid robot can perfectly mimic facial expressions and emotional responses',
    media: 'https://source.unsplash.com/random/600x400?humanoidrobot',
    time: '1d',
    likes: 87654,
    comments: 6543,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e132',
    type: 'video',
    category: 'sports',
    user: {
      name: 'Sports Science',
      username: 'sportsscience',
      avatar: 'https://i.pravatar.cc/150?img=20',
      verified: true,
    },
    content: 'The physics behind why a curveball curves - explained with high-speed cameras',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?baseball',
    duration: '4:56',
    time: '2d',
    likes: 54321,
    comments: 3210,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e133',
    type: 'gallery',
    category: 'architecture',
    user: {
      name: 'Architectural Digest',
      username: 'architecturaldigest',
      avatar: 'https://i.pravatar.cc/150?img=32',
      verified: true,
    },
    content: 'Homes built in extreme locations that defy conventional architecture',
    media: [
      'https://source.unsplash.com/random/600x400?extremehome1',
      'https://source.unsplash.com/random/600x400?extremehome2',
      'https://source.unsplash.com/random/600x400?extremehome3'
    ],
    time: '3d',
    likes: 98765,
    comments: 7654,
    shares: 32109,
    trending: true,
  },
  {
    id: 'e134',
    type: 'note',
    category: 'selfimprovement',
    user: {
      name: 'Better Self',
      username: 'betterself',
      avatar: 'https://i.pravatar.cc/150?img=16',
      verified: true,
    },
    content: '✨ Digital Detox Challenge ✨\n\nDay 1: No social media\nDay 2: Phone-free meals\nDay 3: No screens after 8pm\nDay 4: Read a physical book\nDay 5: Nature walk without devices\n\nWho is joining me?',
    background: 'linear-gradient(120deg, #e0c3fc 0%, #8ec5fc 100%)',
    textColor: 'dark',
    time: '4d',
    likes: 65432,
    comments: 5678,
    shares: 12543,
    trending: true,
  },
  {
    id: 'e135',
    type: 'image',
    category: 'medicine',
    user: {
      name: 'Medical Breakthroughs',
      username: 'medicalbreakthroughs',
      avatar: 'https://i.pravatar.cc/150?img=58',
      verified: true,
    },
    content: 'New microscopic robots can be injected into the bloodstream to target and remove cancer cells',
    media: 'https://source.unsplash.com/random/600x400?medicaltech',
    time: '5d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  },
  {
    id: 'e136',
    type: 'video',
    category: 'astronomy',
    user: {
      name: 'Universe Today',
      username: 'universetoday',
      avatar: 'https://i.pravatar.cc/150?img=46',
      verified: true,
    },
    content: 'This visualization shows what happens when two neutron stars collide',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?spacecollision',
    duration: '5:24',
    time: '6d',
    likes: 87654,
    comments: 6543,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e137',
    type: 'gallery',
    category: 'fashion',
    user: {
      name: 'Fashion Week',
      username: 'fashionweek',
      avatar: 'https://i.pravatar.cc/150?img=31',
      verified: true,
    },
    content: 'Futuristic fashion designs that incorporate wearable technology and adaptive materials',
    media: [
      'https://source.unsplash.com/random/600x400?techfashion1',
      'https://source.unsplash.com/random/600x400?techfashion2',
      'https://source.unsplash.com/random/600x400?techfashion3',
      'https://source.unsplash.com/random/600x400?techfashion4'
    ],
    time: '7d',
    likes: 76543,
    comments: 5432,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e138',
    type: 'image',
    category: 'photography',
    user: {
      name: 'Drone Photography',
      username: 'dronephotography',
      avatar: 'https://i.pravatar.cc/150?img=29',
      verified: true,
    },
    content: 'Aerial view of geometric crop patterns in the Netherlands that look like abstract art',
    media: 'https://source.unsplash.com/random/600x400?aerialcrops',
    time: '8d',
    likes: 98765,
    comments: 8765,
    shares: 43210,
    trending: true,
  },
  {
    id: 'e139',
    type: 'video',
    category: 'biology',
    user: {
      name: 'Biology Visualized',
      username: 'biologyvisualized',
      avatar: 'https://i.pravatar.cc/150?img=54',
      verified: true,
    },
    content: 'Microscopic footage of immune cells chasing and destroying bacteria in real-time',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?immune',
    duration: '3:47',
    time: '9d',
    likes: 87654,
    comments: 7654,
    shares: 32109,
    trending: true,
  },
  {
    id: 'e140',
    type: 'note',
    category: 'philosophy',
    user: {
      name: 'Philosophy Hub',
      username: 'philosophyhub',
      avatar: 'https://i.pravatar.cc/150?img=49',
      verified: true,
    },
    content: '✨ Thought Experiment ✨\n\nIf you could know the absolute truth about one thing in the universe, what would you choose to know?\n\nShare your answers below.',
    background: 'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
    textColor: 'light',
    time: '10d',
    likes: 65432,
    comments: 9876,
    shares: 12345,
    trending: true,
  },
  
  // Final set of posts e141-e150
  {
    id: 'e141',
    type: 'image',
    category: 'history',
    user: {
      name: 'Archaeological Finds',
      username: 'archaeologicalfinds',
      avatar: 'https://i.pravatar.cc/150?img=37',
      verified: true,
    },
    content: 'Recently unearthed ancient city that rewrites our understanding of early human civilization',
    media: 'https://source.unsplash.com/random/600x400?ancientcity',
    time: '11d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  },
  {
    id: 'e142',
    type: 'video',
    category: 'engineering',
    user: {
      name: 'Engineering Marvels',
      username: 'engineeringmarvels',
      avatar: 'https://i.pravatar.cc/150?img=22',
      verified: true,
    },
    content: 'How engineers built a floating skyscraper that can withstand category 5 hurricanes',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?engineeringmarvel',
    duration: '9:12',
    time: '12d',
    likes: 87654,
    comments: 7654,
    shares: 32109,
    trending: true,
  },
  {
    id: 'e143',
    type: 'gallery',
    category: 'wildlife',
    user: {
      name: 'Animal Behavior',
      username: 'animalbehavior',
      avatar: 'https://i.pravatar.cc/150?img=42',
      verified: true,
    },
    content: 'Rare intelligence tests showing ravens solving complex multi-step puzzles',
    media: [
      'https://source.unsplash.com/random/600x400?raven1',
      'https://source.unsplash.com/random/600x400?raven2',
      'https://source.unsplash.com/random/600x400?raven3'
    ],
    time: '13d',
    likes: 65432,
    comments: 5432,
    shares: 13456,
    trending: true,
  },
  {
    id: 'e144',
    type: 'note',
    category: 'health',
    user: {
      name: 'Holistic Health',
      username: 'holistichealth',
      avatar: 'https://i.pravatar.cc/150?img=40',
      verified: true,
    },
    content: '✨ Morning Routine for Optimal Health ✨\n\n1. Warm lemon water\n2. 15 min stretching\n3. Cold shower\n4. Protein-rich breakfast\n5. 10 min mindfulness\n\nSmall habits, big results.',
    background: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    textColor: 'dark',
    time: '14d',
    likes: 98765,
    comments: 8765,
    shares: 43210,
    trending: true,
  },
  {
    id: 'e145',
    type: 'image',
    category: 'climate',
    user: {
      name: 'Climate Solutions',
      username: 'climatesolutions',
      avatar: 'https://i.pravatar.cc/150?img=25',
      verified: true,
    },
    content: 'This massive carbon capture facility can remove CO2 equivalent to 40 million trees',
    media: 'https://source.unsplash.com/random/600x400?carboncapture',
    time: '15d',
    likes: 65432,
    comments: 4321,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e146',
    type: 'video',
    category: 'music',
    user: {
      name: 'Music Analysis',
      username: 'musicanalysis',
      avatar: 'https://i.pravatar.cc/150?img=38',
      verified: true,
    },
    content: 'The mathematical patterns behind why certain melodies get stuck in your head',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?musictheory',
    duration: '7:28',
    time: '16d',
    likes: 76543,
    comments: 5432,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e147',
    type: 'gallery',
    category: 'artinstallation',
    user: {
      name: 'Installation Art',
      username: 'installationart',
      avatar: 'https://i.pravatar.cc/150?img=27',
      verified: true,
    },
    content: 'This interactive light installation responds to human emotions and creates unique patterns',
    media: [
      'https://source.unsplash.com/random/600x400?lightinstallation1',
      'https://source.unsplash.com/random/600x400?lightinstallation2',
      'https://source.unsplash.com/random/600x400?lightinstallation3',
      'https://source.unsplash.com/random/600x400?lightinstallation4'
    ],
    time: '17d',
    likes: 98765,
    comments: 7654,
    shares: 34567,
    trending: true,
  },
  {
    id: 'e148',
    type: 'image',
    category: 'archaeology',
    user: {
      name: 'Time Capsule',
      username: 'timecapsule',
      avatar: 'https://i.pravatar.cc/150?img=36',
      verified: true,
    },
    content: 'Perfectly preserved 2,000-year-old Roman mosaic floor discovered under a vineyard',
    media: 'https://source.unsplash.com/random/600x400?romanmosaic',
    time: '18d',
    likes: 123456,
    comments: 9876,
    shares: 54321,
    trending: true,
  },
  {
    id: 'e149',
    type: 'video',
    category: 'physics',
    user: {
      name: 'Physics Explained',
      username: 'physicsexplained',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'What happens when you fire a gun underwater? High-speed camera reveals fascinating physics',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?waterphysics',
    duration: '6:52',
    time: '19d',
    likes: 87654,
    comments: 6543,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e150',
    type: 'note',
    category: 'motivation',
    user: {
      name: 'Success Mindset',
      username: 'successmindset',
      avatar: 'https://i.pravatar.cc/150?img=33',
      verified: true,
    },
    content: '✨ Three Questions for Growth ✨\n\n1. What did I learn today?\n2. How did I help someone?\n3. What am I grateful for?\n\nAnswer these every night for 30 days and watch your perspective transform.',
    background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    textColor: 'dark',
    time: '20d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  }
];

export default combinedExplorePosts; 