import React from 'react';

// Additional explore posts to be combined with existing posts
const additionalExplorePosts = [
  {
    id: 'e39',
    type: 'gallery',
    category: 'streetfood',
    user: {
      name: 'Street Food Explorer',
      username: 'streetfoodexplorer',
      avatar: 'https://i.pravatar.cc/150?img=43',
      verified: true,
    },
    content: 'Street food markets in Asia that will blow your taste buds away 🌮🍜',
    media: [
      'https://source.unsplash.com/random/600x400?streetfood1',
      'https://source.unsplash.com/random/600x400?streetfood2',
      'https://source.unsplash.com/random/600x400?streetfood3'
    ],
    time: '24d',
    likes: 9876,
    comments: 456,
    shares: 789,
    trending: true,
  },
  {
    id: 'e40',
    type: 'short',
    category: 'lifehack',
    user: {
      name: 'Life Hacker',
      username: 'lifehacker',
      avatar: 'https://i.pravatar.cc/150?img=55',
      verified: true,
    },
    content: 'How to fold a fitted sheet perfectly in under 30 seconds! ✨',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?housework',
    duration: '0:25',
    time: '25d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e41',
    type: 'image',
    category: 'art',
    user: {
      name: 'Art Gallery',
      username: 'artgallery',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'Contemporary art installation that plays with light and shadows',
    media: 'https://source.unsplash.com/random/600x400?contemporaryart',
    time: '1d',
    likes: 12543,
    comments: 783,
    shares: 2145,
    trending: true,
  },
  {
    id: 'e42',
    type: 'video',
    category: 'science',
    user: {
      name: 'Science Today',
      username: 'sciencetoday',
      avatar: 'https://i.pravatar.cc/150?img=62',
      verified: true,
    },
    content: 'Watch what happens when you mix these two chemicals together! 🧪',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?chemistry',
    duration: '3:45',
    time: '2d',
    likes: 9875,
    comments: 876,
    shares: 1432,
    trending: true,
  },
  {
    id: 'e43',
    type: 'note',
    category: 'philosophy',
    user: {
      name: 'Deep Thoughts',
      username: 'deepthoughts',
      avatar: 'https://i.pravatar.cc/150?img=39',
      verified: true,
    },
    content: '✨ Philosophical Question ✨\n\n"If a tree falls in a forest and no one is around to hear it, does it make a sound?"\n\nWhat are your thoughts?',
    background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    textColor: 'dark',
    time: '3d',
    likes: 8765,
    comments: 1543,
    shares: 432,
    trending: true,
  },
  {
    id: 'e44',
    type: 'gallery',
    category: 'fashion',
    user: {
      name: 'Fashion Week',
      username: 'fashionweek',
      avatar: 'https://i.pravatar.cc/150?img=29',
      verified: true,
    },
    content: 'Top trends from this year\'s Paris Fashion Week 👗',
    media: [
      'https://source.unsplash.com/random/600x400?fashionshow1',
      'https://source.unsplash.com/random/600x400?fashionshow2',
      'https://source.unsplash.com/random/600x400?fashionshow3',
      'https://source.unsplash.com/random/600x400?fashionshow4'
    ],
    time: '4d',
    likes: 23456,
    comments: 876,
    shares: 1234,
    trending: true,
  },
  {
    id: 'e45',
    type: 'short',
    category: 'pets',
    user: {
      name: 'Pet Lovers',
      username: 'petlovers',
      avatar: 'https://i.pravatar.cc/150?img=14',
      verified: true,
    },
    content: 'This dog\'s reaction when his owner comes home after 6 months 😭',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?dog',
    duration: '0:28',
    time: '5d',
    likes: 45678,
    comments: 3456,
    shares: 7654,
    trending: true,
  },
  {
    id: 'e46',
    type: 'audio',
    category: 'education',
    user: {
      name: 'Learn Daily',
      username: 'learndaily',
      avatar: 'https://i.pravatar.cc/150?img=22',
      verified: true,
    },
    content: 'Learn a new language in your sleep with these proven techniques',
    media: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
    duration: '22:15',
    visualizer: true,
    time: '6d',
    likes: 7654,
    comments: 987,
    shares: 1234,
    trending: true,
  },
  {
    id: 'e47',
    type: 'image',
    category: 'architecture',
    user: {
      name: 'Urban Planning',
      username: 'urbanplanning',
      avatar: 'https://i.pravatar.cc/150?img=33',
      verified: true,
    },
    content: 'Revolutionary sustainable building design that produces more energy than it consumes',
    media: 'https://source.unsplash.com/random/600x400?sustainable',
    time: '7d',
    likes: 12345,
    comments: 876,
    shares: 2345,
    trending: true,
  },
  {
    id: 'e48',
    type: 'video',
    category: 'DIY',
    user: {
      name: 'DIY Master',
      username: 'diymaster',
      avatar: 'https://i.pravatar.cc/150?img=42',
      verified: true,
    },
    content: 'How to build a stunning bookshelf from reclaimed wood in one weekend',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?woodworking',
    duration: '12:32',
    time: '8d',
    likes: 8765,
    comments: 1234,
    shares: 3456,
    trending: true,
  },
  {
    id: 'e49',
    type: 'note',
    category: 'motivation',
    user: {
      name: 'Motivation Coach',
      username: 'motivationcoach',
      avatar: 'https://i.pravatar.cc/150?img=53',
      verified: true,
    },
    content: '🔥 Daily Motivation 🔥\n\n"The only way to do great work is to love what you do." - Steve Jobs\n\nWhat are you passionate about?',
    background: 'linear-gradient(120deg, #ff9a9e 0%, #fad0c4 100%)',
    textColor: 'dark',
    time: '9d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e50',
    type: 'gallery',
    category: 'travel',
    user: {
      name: 'Adventure Seeker',
      username: 'adventureseeker',
      avatar: 'https://i.pravatar.cc/150?img=64',
      verified: true,
    },
    content: 'Hidden waterfalls in South America that you need to visit at least once in your lifetime',
    media: [
      'https://source.unsplash.com/random/600x400?waterfall1',
      'https://source.unsplash.com/random/600x400?waterfall2',
      'https://source.unsplash.com/random/600x400?waterfall3'
    ],
    time: '10d',
    likes: 23456,
    comments: 1234,
    shares: 3456,
    trending: true,
  },
  {
    id: 'e51',
    type: 'short',
    category: 'sports',
    user: {
      name: 'Sports Highlights',
      username: 'sportshighlights',
      avatar: 'https://i.pravatar.cc/150?img=17',
      verified: true,
    },
    content: 'Most incredible buzzer beater in basketball history! 🏀',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?basketball',
    duration: '0:22',
    time: '11d',
    likes: 67890,
    comments: 5432,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e52',
    type: 'audio',
    category: 'storytelling',
    user: {
      name: 'Storyteller',
      username: 'storyteller',
      avatar: 'https://i.pravatar.cc/150?img=26',
      verified: true,
    },
    content: 'Haunting ghost story that will keep you up at night',
    media: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
    duration: '15:48',
    visualizer: true,
    time: '12d',
    likes: 12345,
    comments: 987,
    shares: 1456,
    trending: true,
  }
];

export default additionalExplorePosts; 