import React from 'react';

// Combined explore posts from all previous files
const combinedExplorePosts = [
  {
    id: 'e151',
    type: 'image',
    category: 'travel',
    user: {
      name: 'Globetrotter',
      username: 'worldwanderer',
      avatar: 'https://i.pravatar.cc/150?img=11',
      verified: true,
    },
    content: 'Sunrise over the ancient temples of Bagan, Myanmar. A landscape that takes your breath away.',
    media: 'https://source.unsplash.com/random/1000x1000?bagan,myanmar,temples',
    time: '1d',
    likes: 28541,
    comments: 789,
    shares: 3452,
    trending: true,
  },
  {
    id: 'e152',
    type: 'video',
    category: 'nature',
    user: {
      name: 'Wild Planet',
      username: 'wildplanet',
      avatar: 'https://i.pravatar.cc/150?img=12',
      verified: true,
    },
    content: 'Rare footage of a snow leopard hunting in the Himalayas. These elusive cats are masters of camouflage.',
    media: 'https://source.unsplash.com/random/1000x1000?snow,leopard',
    thumbnail: 'https://source.unsplash.com/random/1000x1000?snow,leopard',
    duration: '3:24',
    time: '2d',
    likes: 45672,
    comments: 1234,
    shares: 8976,
    trending: true,
  },
  {
    id: 'e154',
    type: 'carousel',
    category: 'food',
    user: {
      name: 'Culinary Journeys',
      username: 'foodexplorer',
      avatar: 'https://i.pravatar.cc/150?img=14',
      verified: true,
    },
    content: 'The art of Japanese wagyu beef preparation. From farm to plate, every step is a ritual.',
    media: [
      'https://source.unsplash.com/random/1000x1000?wagyu,beef,raw',
      'https://source.unsplash.com/random/1000x1000?wagyu,beef,cooking',
      'https://source.unsplash.com/random/1000x1000?wagyu,beef,plated'
    ],
    time: '8h',
    likes: 32456,
    comments: 876,
    shares: 4321,
    trending: true,
  },
  {
    id: 'e155',
    type: 'note',
    category: 'poetry',
    user: {
      name: 'Verses & Rhymes',
      username: 'poetryinmotion',
      avatar: 'https://i.pravatar.cc/150?img=15',
      verified: false,
    },
    content: 'In the silence between heartbeats\nI found a universe untouched\nBy human hands or thoughts\nA sanctuary of infinite possibilities',
    background: 'linear-gradient(135deg, #6e8efb 0%, #a777e3 100%)',
    textColor: 'white',
    time: '12h',
    likes: 15678,
    comments: 423,
    shares: 2876,
    trending: false,
  },
  {
    id: 'e157',
    type: 'image',
    category: 'fashion',
    user: {
      name: 'Style Chronicles',
      username: 'fashionforward',
      avatar: 'https://i.pravatar.cc/150?img=17',
      verified: true,
    },
    content: 'Sustainable fashion from recycled ocean plastic. The future of ethical couture is here.',
    media: 'https://source.unsplash.com/random/1000x1000?sustainable,fashion,recycled',
    time: '3h',
    likes: 24567,
    comments: 765,
    shares: 2987,
    trending: true,
  },
  {
    id: 'e158',
    type: 'note',
    category: 'psychology',
    user: {
      name: 'Mind Matters',
      username: 'psychinsights',
      avatar: 'https://i.pravatar.cc/150?img=18',
      verified: false,
    },
    content: '5 Cognitive Biases That Shape Your Reality:\n\n1. Confirmation Bias\n2. Availability Heuristic\n3. Dunning-Kruger Effect\n4. Negativity Bias\n5. Sunk Cost Fallacy\n\nWhich one affects you the most?',
    background: 'linear-gradient(120deg, #f093fb 0%, #f5576c 100%)',
    textColor: 'white',
    time: '6h',
    likes: 19876,
    comments: 887,
    shares: 4523,
    trending: false,
  },
  {
    id: 'e160',
    type: 'video',
    category: 'diy',
    user: {
      name: 'Craft Corner',
      username: 'diycreator',
      avatar: 'https://i.pravatar.cc/150?img=20',
      verified: false,
    },
    content: 'Turn an old wooden pallet into a stylish outdoor coffee table in just 30 minutes. No special tools required!',
    media: 'https://source.unsplash.com/random/1000x1000?wooden,pallet,diy',
    thumbnail: 'https://source.unsplash.com/random/1000x1000?wooden,pallet,diy',
    duration: '7:45',
    time: '4h',
    likes: 12453,
    comments: 534,
    shares: 2876,
    trending: false,
  },
  {
    id: 'e161',
    type: 'image',
    category: 'underwater',
    user: {
      name: 'Ocean Depths',
      username: 'deepblue',
      avatar: 'https://i.pravatar.cc/150?img=21',
      verified: true,
    },
    content: 'A rare encounter with a giant squid in the deep sea. These mysterious creatures can grow up to 43 feet long!',
    media: 'https://source.unsplash.com/random/1000x1000?giant,squid,ocean',
    time: '1d',
    likes: 42987,
    comments: 1234,
    shares: 7865,
    trending: true,
  },
  {
    id: 'e162',
    type: 'note',
    category: 'philosophy',
    user: {
      name: 'Deep Thoughts',
      username: 'philosophy101',
      avatar: 'https://i.pravatar.cc/150?img=22',
      verified: false,
    },
    content: '"We are not human beings having a spiritual experience. We are spiritual beings having a human experience." - Pierre Teilhard de Chardin\n\nHow does this perspective shift your view of life?',
    background: 'linear-gradient(to right, #000428, #004e92)',
    textColor: 'white',
    time: '10h',
    likes: 18765,
    comments: 984,
    shares: 5423,
    trending: false,
  },
  {
    id: 'e165',
    type: 'image',
    category: 'history',
    user: {
      name: 'Time Traveler',
      username: 'historybuff',
      avatar: 'https://i.pravatar.cc/150?img=25',
      verified: false,
    },
    content: 'Recently discovered Viking settlement artifacts in Newfoundland. Rewriting history one discovery at a time.',
    media: 'https://source.unsplash.com/random/1000x1000?viking,artifacts,archaeology',
    time: '5d',
    likes: 17654,
    comments: 765,
    shares: 3421,
    trending: false,
  },
  {
    id: 'e166',
    type: 'note',
    category: 'productivity',
    user: {
      name: 'Optimal Living',
      username: 'productivityguru',
      avatar: 'https://i.pravatar.cc/150?img=26',
      verified: true,
    },
    content: '🔑 The 5-3-1 Method for Decision Making 🔑\n\n5 minutes: Define the decision clearly\n3 options: Always generate exactly 3 alternatives\n1 choice: Commit fully to your decision\n\nSimple yet powerful for overcoming decision paralysis.',
    background: 'linear-gradient(to right, #00b09b, #96c93d)',
    textColor: 'white',
    time: '9h',
    likes: 31254,
    comments: 987,
    shares: 6543,
    trending: true,
  },
  {
    id: 'e167',
    type: 'video',
    category: 'wildlife',
    user: {
      name: 'Wild Chronicles',
      username: 'animalplanet',
      avatar: 'https://i.pravatar.cc/150?img=27',
      verified: true,
    },
    content: 'Wolves howling at twilight in Yellowstone National Park. The sound that brought back an ecosystem.',
    media: 'https://source.unsplash.com/random/1000x1000?wolves,howling,yellowstone',
    thumbnail: 'https://source.unsplash.com/random/1000x1000?wolves,howling,yellowstone',
    duration: '2:15',
    time: '1d',
    likes: 43567,
    comments: 1234,
    shares: 7654,
    trending: true,
  },
  {
    id: 'e168',
    type: 'carousel',
    category: 'technology',
    user: {
      name: 'Future Tech',
      username: 'techinnovator',
      avatar: 'https://i.pravatar.cc/150?img=28',
      verified: true,
    },
    content: 'The evolution of computer processors: from vacuum tubes to quantum computing. 70 years of exponential growth.',
    media: [
      'https://source.unsplash.com/random/1000x1000?vacuum,tube,computer',
      'https://source.unsplash.com/random/1000x1000?transistor,circuit',
      'https://source.unsplash.com/random/1000x1000?microchip,processor',
      'https://source.unsplash.com/random/1000x1000?quantum,computer'
    ],
    time: '6d',
    likes: 35678,
    comments: 1098,
    shares: 6543,
    trending: true,
  },
  {
    id: 'e169',
    type: 'image',
    category: 'sports',
    user: {
      name: 'Sports Lens',
      username: 'actioncapture',
      avatar: 'https://i.pravatar.cc/150?img=29',
      verified: false,
    },
    content: 'The perfect moment: a high diver frozen in mid-air, demonstrating incredible form and control.',
    media: 'https://source.unsplash.com/random/1000x1000?high,diving,sport',
    time: '3h',
    likes: 24567,
    comments: 765,
    shares: 3421,
    trending: false,
  },
  {
    id: 'e170',
    type: 'note',
    category: 'health',
    user: {
      name: 'Wellness Journey',
      username: 'holistichealth',
      avatar: 'https://i.pravatar.cc/150?img=30',
      verified: true,
    },
    content: '💪 Your body can regenerate:\n\n• Liver: 6 weeks\n• Skin: 27 days\n• Stomach lining: 5 days\n• Skeleton: 10 years\n• Red blood cells: 4 months\n\nEvery day is a chance for renewal.',
    background: 'linear-gradient(45deg, #FA8BFF 0%, #2BD2FF 52%, #2BFF88 90%)',
    textColor: 'dark',
    time: '14h',
    likes: 28765,
    comments: 932,
    shares: 5421,
    trending: false,
  },
  {
    id: 'e184',
    type: 'image',
    category: 'festivals',
    user: {
      name: 'Festival Life',
      username: 'celebrationculture',
      avatar: 'https://i.pravatar.cc/150?img=44',
      verified: true,
    },
    content: 'Burning Man from above: a temporary city of 70,000 people that appears and disappears in the Nevada desert.',
    media: 'https://source.unsplash.com/random/1000x1000?burning,man,aerial',
    time: '14d',
    likes: 42987,
    comments: 1543,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e189',
    type: 'note',
    category: 'mathematics',
    user: {
      name: 'Number Theory',
      username: 'mathbeauty',
      avatar: 'https://i.pravatar.cc/150?img=49',
      verified: true,
    },
    content: '🧠 Fascinating Number Patterns 🧠\n\n1, 1, 2, 3, 5, 8, 13... (Fibonacci)\n1, 2, 4, 8, 16, 32... (Powers of 2)\n1, 4, 9, 16, 25, 36... (Perfect squares)\n3, 1, 4, 1, 5, 9... (π digits)\n\nThe universe speaks in mathematics.',
    background: 'linear-gradient(45deg, #654ea3, #eaafc8)',
    textColor: 'white',
    time: '4d',
    likes: 19876,
    comments: 843,
    shares: 4231,
    trending: false,
  },
  {
    id: 'e190',
    type: 'video',
    category: 'cooking',
    user: {
      name: 'Culinary Arts',
      username: 'masterchef',
      avatar: 'https://i.pravatar.cc/150?img=50',
      verified: true,
    },
    content: 'The ancient art of hand-pulled noodles: a technique that takes years to master but only minutes to create.',
    media: 'https://source.unsplash.com/random/1000x1000?hand,pulled,noodles',
    thumbnail: 'https://source.unsplash.com/random/1000x1000?hand,pulled,noodles',
    duration: '6:24',
    time: '2d',
    likes: 32154,
    comments: 987,
    shares: 5432,
    trending: true,
  },
  {
    id: 'e191',
    type: 'image',
    category: 'urban exploration',
    user: {
      name: 'Urban Explorer',
      username: 'cityseeker',
      avatar: 'https://i.pravatar.cc/150?img=51',
      verified: false,
    },
    content: 'Abandoned Olympic venues reclaimed by nature. A powerful reminder of impermanence.',
    media: 'https://source.unsplash.com/random/1000x1000?abandoned,olympic,venue',
    time: '8d',
    likes: 27654,
    comments: 843,
    shares: 5421,
    trending: false,
  },
  {
    id: 'e196',
    type: 'note',
    category: 'psychology',
    user: {
      name: 'Mind Explorer',
      username: 'brainpatterns',
      avatar: 'https://i.pravatar.cc/150?img=56',
      verified: true,
    },
    content: '🧠 Three powerful psychological principles:\n\n1. Parkinson\'s Law: Work expands to fill the time available\n2. Dunbar\'s Number: You can maintain ~150 meaningful relationships\n3. Pareto Principle: 80% of results come from 20% of efforts\n\nWhich one impacts you most?',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    textColor: 'white',
    time: '7h',
    likes: 28765,
    comments: 1243,
    shares: 6543,
    trending: false,
  },
  {
    id: 'e197',
    type: 'carousel',
    category: 'design',
    user: {
      name: 'Design Thinking',
      username: 'creativedesigner',
      avatar: 'https://i.pravatar.cc/150?img=57',
      verified: true,
    },
    content: 'Award-winning chairs that redefined furniture design. The perfect balance of form and function.',
    media: [
      'https://source.unsplash.com/random/1000x1000?iconic,chair,design,1',
      'https://source.unsplash.com/random/1000x1000?iconic,chair,design,2',
      'https://source.unsplash.com/random/1000x1000?iconic,chair,design,3',
      'https://source.unsplash.com/random/1000x1000?iconic,chair,design,4'
    ],
    time: '9d',
    likes: 24567,
    comments: 876,
    shares: 4321,
    trending: true,
  },
  {
    id: 'e198',
    type: 'video',
    category: 'wildlife',
    user: {
      name: 'Wild Earth',
      username: 'animalplanet',
      avatar: 'https://i.pravatar.cc/150?img=58',
      verified: true,
    },
    content: 'Elephants mourning their dead: compelling evidence of complex emotions in non-human animals.',
    media: 'https://source.unsplash.com/random/1000x1000?elephants,mourning',
    thumbnail: 'https://source.unsplash.com/random/1000x1000?elephants,mourning',
    duration: '5:18',
    time: '6d',
    likes: 43567,
    comments: 1765,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e199',
    type: 'image',
    category: 'astronomy',
    user: {
      name: 'Cosmic Voyager',
      username: 'deepspace',
      avatar: 'https://i.pravatar.cc/150?img=59',
      verified: true,
    },
    content: 'The Pillars of Creation: where stars are born in the Eagle Nebula, 7,000 light-years from Earth.',
    media: 'https://source.unsplash.com/random/1000x1000?pillars,creation,nebula',
    time: '12d',
    likes: 53421,
    comments: 1987,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e247',
    type: 'gallery',
    category: 'artinstallation',
    user: {
      name: 'Installation Art',
      username: 'installationart',
      avatar: 'https://i.pravatar.cc/150?img=27',
      verified: true,
    },
    content: 'This interactive light installation responds to human emotions and creates unique patterns',
    media: [
      'https://source.unsplash.com/random/600x400?lightinstallation1',
      'https://source.unsplash.com/random/600x400?lightinstallation2',
      'https://source.unsplash.com/random/600x400?lightinstallation3',
      'https://source.unsplash.com/random/600x400?lightinstallation4'
    ],
    time: '17d',
    likes: 98765,
    comments: 7654,
    shares: 34567,
    trending: true,
  },
  {
    id: 'e248',
    type: 'image',
    category: 'archaeology',
    user: {
      name: 'Time Capsule',
      username: 'timecapsule',
      avatar: 'https://i.pravatar.cc/150?img=36',
      verified: true,
    },
    content: 'Perfectly preserved 2,000-year-old Roman mosaic floor discovered under a vineyard',
    media: 'https://source.unsplash.com/random/600x400?romanmosaic',
    time: '18d',
    likes: 123456,
    comments: 9876,
    shares: 54321,
    trending: true,
  },
  {
    id: 'e249',
    type: 'video',
    category: 'physics',
    user: {
      name: 'Physics Explained',
      username: 'physicsexplained',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'What happens when you fire a gun underwater? High-speed camera reveals fascinating physics',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?waterphysics',
    duration: '6:52',
    time: '19d',
    likes: 87654,
    comments: 6543,
    shares: 23456,
    trending: true,
  },
  {
    id: 'e250',
    type: 'note',
    category: 'motivation',
    user: {
      name: 'Success Mindset',
      username: 'successmindset',
      avatar: 'https://i.pravatar.cc/150?img=33',
      verified: true,
    },
    content: '✨ Three Questions for Growth ✨\n\n1. What did I learn today?\n2. How did I help someone?\n3. What am I grateful for?\n\nAnswer these every night for 30 days and watch your perspective transform.',
    background: 'linear-gradient(120deg, #a1c4fd 0%, #c2e9fb 100%)',
    textColor: 'dark',
    time: '20d',
    likes: 123456,
    comments: 9876,
    shares: 45678,
    trending: true,
  },
  {
    id: 'e251',
    type: 'image',
    category: 'technology',
    user: {
      name: 'Quantum Tech',
      username: 'quantumtech',
      avatar: 'https://i.pravatar.cc/150?img=21',
      verified: true,
    },
    content: 'First commercial quantum computer that can solve problems traditional computers find impossible',
    media: 'https://source.unsplash.com/random/600x400?quantumcomputer',
    time: '20d',
    likes: 123456,
    comments: 7890,
    shares: 34567,
    trending: true,
  },
  {
    id: 'e252',
    type: 'video',
    category: 'nature',
    user: {
      name: 'Nature Timelapse',
      username: 'naturetimelapse',
      avatar: 'https://i.pravatar.cc/150?img=15',
      verified: true,
    },
    content: 'Blooming flowers captured in 8K timelapse over 30 days and compressed to 2 minutes',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?flowertimelapse',
    duration: '2:15',
    time: '21d',
    likes: 87654,
    comments: 5432,
    shares: 12345,
    trending: true,
  },
  {
    id: 'e253',
    type: 'gallery',
    category: 'photography',
    user: {
      name: 'Macro Photo',
      username: 'macrophoto',
      avatar: 'https://i.pravatar.cc/150?img=9',
      verified: true,
    },
    content: 'The hidden world of insects - captured with specialized macro photography',
    media: [
      'https://source.unsplash.com/random/600x400?insectmacro1',
      'https://source.unsplash.com/random/600x400?insectmacro2',
      'https://source.unsplash.com/random/600x400?insectmacro3'
    ],
    time: '22d',
    likes: 65432,
    comments: 4321,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e254',
    type: 'note',
    category: 'finance',
    user: {
      name: 'Money Matters',
      username: 'moneymatters',
      avatar: 'https://i.pravatar.cc/150?img=19',
      verified: true,
    },
    content: '✨ Financial Freedom Rules ✨\n\n1. Spend less than you earn\n2. Invest the difference\n3. Avoid debt\n4. Build multiple income streams\n5. Protect your assets\n\nWhich one are you working on right now?',
    background: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    textColor: 'dark',
    time: '23d',
    likes: 98765,
    comments: 7654,
    shares: 23456,
    trending: true,
  },
];

// Create the ExplorePosts component
const ExplorePosts = () => {
  return (
    <div className="explore-posts">
      {/* You can render your posts here */}
      {combinedExplorePosts.map(post => (
        <div key={post.id} className="post-card">
          <div className="post-header">
            <img src={post.user.avatar} alt={post.user.name} className="user-avatar" />
            <div className="user-info">
              <h3>{post.user.name} {post.user.verified && '✓'}</h3>
              <p>@{post.user.username} • {post.time}</p>
            </div>
          </div>
          <p className="post-content">{post.content}</p>
          {post.type === 'image' && (
            <img src={post.media} alt="Post media" className="post-media" />
          )}
          {/* Additional rendering for other post types could be added here */}
          <div className="post-stats">
            <span>❤️ {post.likes}</span>
            <span>💬 {post.comments}</span>
            <span>🔄 {post.shares}</span>
          </div>
        </div>
      ))}
    </div>
  );
};

// Export both the component and the data array
export { combinedExplorePosts };
export default ExplorePosts;