import React from 'react';

// More additional explore posts to be combined with existing posts
const moreExplorePosts = [
  {
    id: 'e53',
    type: 'image',
    category: 'nature',
    user: {
      name: 'Nature Photography',
      username: 'naturephotography',
      avatar: 'https://i.pravatar.cc/150?img=37',
      verified: true,
    },
    content: 'Rare phenomenon: bioluminescent plankton lighting up the beach at night',
    media: 'https://source.unsplash.com/random/600x400?bioluminescent',
    time: '13d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e54',
    type: 'video',
    category: 'astronomy',
    user: {
      name: 'Space Explorer',
      username: 'spaceexplorer',
      avatar: 'https://i.pravatar.cc/150?img=48',
      verified: true,
    },
    content: 'Meteor shower timelapse captured from the mountains - no filters used!',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?meteor',
    duration: '2:30',
    time: '14d',
    likes: 45678,
    comments: 3456,
    shares: 7890,
    trending: true,
  },
  {
    id: 'e55',
    type: 'note',
    category: 'poetry',
    user: {
      name: 'Poet Soul',
      username: 'poetsoul',
      avatar: 'https://i.pravatar.cc/150?img=59',
      verified: true,
    },
    content: '✨ Midnight Thoughts ✨\n\nStars whisper secrets,\nMoon keeps them safe,\nNight fades to dawn,\nBut memories remain.',
    background: 'linear-gradient(120deg, #8ec5fc 0%, #e0c3fc 100%)',
    textColor: 'dark',
    time: '15d',
    likes: 9876,
    comments: 654,
    shares: 321,
    trending: true,
  },
  {
    id: 'e56',
    type: 'gallery',
    category: 'interior',
    user: {
      name: 'Interior Design',
      username: 'interiordesign',
      avatar: 'https://i.pravatar.cc/150?img=13',
      verified: true,
    },
    content: 'Minimalist interior design trends that create space and tranquility',
    media: [
      'https://source.unsplash.com/random/600x400?interior1',
      'https://source.unsplash.com/random/600x400?interior2',
      'https://source.unsplash.com/random/600x400?interior3',
      'https://source.unsplash.com/random/600x400?interior4'
    ],
    time: '16d',
    likes: 12345,
    comments: 876,
    shares: 2345,
    trending: true,
  },
  {
    id: 'e57',
    type: 'short',
    category: 'comedy',
    user: {
      name: 'Comedy Club',
      username: 'comedyclub',
      avatar: 'https://i.pravatar.cc/150?img=24',
      verified: true,
    },
    content: 'The most hilarious stand-up joke that has everyone laughing uncontrollably 😂',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?microphone',
    duration: '0:45',
    time: '17d',
    likes: 78901,
    comments: 6543,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e58',
    type: 'audio',
    category: 'health',
    user: {
      name: 'Wellness Coach',
      username: 'wellnesscoach',
      avatar: 'https://i.pravatar.cc/150?img=35',
      verified: true,
    },
    content: 'Guided meditation for anxiety relief and better sleep quality',
    media: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
    duration: '18:20',
    visualizer: true,
    time: '18d',
    likes: 7654,
    comments: 321,
    shares: 987,
    trending: true,
  },
  {
    id: 'e59',
    type: 'image',
    category: 'wildlife',
    user: {
      name: 'Wildlife Photographer',
      username: 'wildlifephotographer',
      avatar: 'https://i.pravatar.cc/150?img=46',
      verified: true,
    },
    content: 'Extremely rare white tiger spotted in the wild - only 8 known to exist',
    media: 'https://source.unsplash.com/random/600x400?tiger',
    time: '19d',
    likes: 45678,
    comments: 3456,
    shares: 7890,
    trending: true,
  },
  {
    id: 'e60',
    type: 'video',
    category: 'technology',
    user: {
      name: 'Tech Innovations',
      username: 'techinnovations',
      avatar: 'https://i.pravatar.cc/150?img=57',
      verified: true,
    },
    content: 'AI robot completes parkour course faster than human athletes!',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?robot',
    duration: '4:56',
    time: '20d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e61',
    type: 'note',
    category: 'finance',
    user: {
      name: 'Finance Advisor',
      username: 'financeadvisor',
      avatar: 'https://i.pravatar.cc/150?img=68',
      verified: true,
    },
    content: '💰 Money Tip 💰\n\nInvest 20% of your income before spending on wants. Your future self will thank you.\n\nWhat\'s your best financial advice?',
    background: 'linear-gradient(120deg, #84fab0 0%, #8fd3f4 100%)',
    textColor: 'dark',
    time: '21d',
    likes: 7654,
    comments: 543,
    shares: 987,
    trending: true,
  },
  {
    id: 'e62',
    type: 'gallery',
    category: 'food',
    user: {
      name: 'Food Critic',
      username: 'foodcritic',
      avatar: 'https://i.pravatar.cc/150?img=32',
      verified: true,
    },
    content: 'Michelin star desserts that look too good to eat',
    media: [
      'https://source.unsplash.com/random/600x400?dessert1',
      'https://source.unsplash.com/random/600x400?dessert2',
      'https://source.unsplash.com/random/600x400?dessert3'
    ],
    time: '22d',
    likes: 23456,
    comments: 1234,
    shares: 3456,
    trending: true,
  },
  {
    id: 'e63',
    type: 'short',
    category: 'magic',
    user: {
      name: 'Magic Tricks',
      username: 'magictricks',
      avatar: 'https://i.pravatar.cc/150?img=42',
      verified: true,
    },
    content: 'The card trick that fooled the world\'s best magicians',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?cards',
    duration: '0:38',
    time: '23d',
    likes: 56789,
    comments: 4321,
    shares: 8765,
    trending: true,
  },
  {
    id: 'e64',
    type: 'image',
    category: 'culture',
    user: {
      name: 'Cultural Insights',
      username: 'culturalinsights',
      avatar: 'https://i.pravatar.cc/150?img=52',
      verified: true,
    },
    content: 'Ancient traditions that are still practiced today in modern society',
    media: 'https://source.unsplash.com/random/600x400?tradition',
    time: '24d',
    likes: 12345,
    comments: 876,
    shares: 2345,
    trending: true,
  },
  {
    id: 'e65',
    type: 'video',
    category: 'dance',
    user: {
      name: 'Dance Evolution',
      username: 'danceevolution',
      avatar: 'https://i.pravatar.cc/150?img=63',
      verified: true,
    },
    content: 'Evolution of hip-hop dance from the 1970s to today in 5 minutes',
    media: 'https://player.vimeo.com/video/484627918?h=6c109e263e&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?hiphop',
    duration: '5:00',
    time: '25d',
    likes: 67890,
    comments: 5432,
    shares: 9876,
    trending: true,
  },
  {
    id: 'e66',
    type: 'audio',
    category: 'interview',
    user: {
      name: 'Celebrity Interviews',
      username: 'celebrityinterviews',
      avatar: 'https://i.pravatar.cc/150?img=19',
      verified: true,
    },
    content: 'Exclusive interview with the Oscar-winning actor about their upcoming film',
    media: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
    duration: '28:45',
    visualizer: true,
    time: '26d',
    likes: 89012,
    comments: 6543,
    shares: 12098,
    trending: true,
  },
  {
    id: 'e67',
    type: 'note',
    category: 'quotes',
    user: {
      name: 'Quotable',
      username: 'quotable',
      avatar: 'https://i.pravatar.cc/150?img=27',
      verified: true,
    },
    content: '🌠 Words of Wisdom 🌠\n\n"In the end, we will remember not the words of our enemies, but the silence of our friends." - Martin Luther King Jr.',
    background: 'linear-gradient(120deg, #a6c0fe 0%, #f68084 100%)',
    textColor: 'light',
    time: '27d',
    likes: 23456,
    comments: 1234,
    shares: 3456,
    trending: true,
  },
  {
    id: 'e68',
    type: 'gallery',
    category: 'photography',
    user: {
      name: 'Photo Artist',
      username: 'photoartist',
      avatar: 'https://i.pravatar.cc/150?img=38',
      verified: true,
    },
    content: 'Breathtaking photos taken at the exact right moment',
    media: [
      'https://source.unsplash.com/random/600x400?moment1',
      'https://source.unsplash.com/random/600x400?moment2',
      'https://source.unsplash.com/random/600x400?moment3',
      'https://source.unsplash.com/random/600x400?moment4'
    ],
    time: '28d',
    likes: 34567,
    comments: 2345,
    shares: 6789,
    trending: true,
  },
  {
    id: 'e69',
    type: 'short',
    category: 'animals',
    user: {
      name: 'Animal Facts',
      username: 'animalfacts',
      avatar: 'https://i.pravatar.cc/150?img=49',
      verified: true,
    },
    content: 'This endangered species was thought to be extinct until it was spotted last week! 🦊',
    media: 'https://player.vimeo.com/video/559163669?h=78e7685dd2&title=0&byline=0&portrait=0',
    thumbnail: 'https://source.unsplash.com/random/600x400?wildlife',
    duration: '0:32',
    time: '29d',
    likes: 45678,
    comments: 3456,
    shares: 7890,
    trending: true,
  },
  {
    id: 'e70',
    type: 'image',
    category: 'weather',
    user: {
      name: 'Weather Chasers',
      username: 'weatherchasers',
      avatar: 'https://i.pravatar.cc/150?img=60',
      verified: true,
    },
    content: 'Incredible supercell thunderstorm captured in the Great Plains yesterday',
    media: 'https://source.unsplash.com/random/600x400?thunderstorm',
    time: '30d',
    likes: 56789,
    comments: 4321,
    shares: 8765,
    trending: true,
  }
];

export default moreExplorePosts; 